name: markdownlint
on: [push, pull_request]
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Lint markdown
      uses: DavidAnson/markdownlint-cli2-action@v19
      with:
        config: .markdownlint.yml
        globs: '*.md,translations/*.md,Comanche055/*.md,Luminary099/*.md'
        separator: ','
